/**
 * subjectsData.js
 * Central data store for all subjects, their details, and YouTube resources.
 * Place at: src/data/subjectsData.js
 */

export const subjects = [
  {
    id: "engineering-mathematics",
    icon: "Calculator",
    accentColor: "#4f8ef7",
    accentBg: "rgba(79,142,247,0.12)",
    title: "Engineering Mathematics",
    tagline: "The language every engineer must speak.",
    description:
      "Master calculus, linear algebra, differential equations, and transforms that form the mathematical backbone of all engineering disciplines.",
    topics: [
      "Differential Calculus — limits, derivatives, applications",
      "Integral Calculus — definite, indefinite, area/volume",
      "Matrices & Determinants — row ops, eigenvalues",
      "Differential Equations — 1st & 2nd order methods",
      "Laplace & Fourier Transforms",
      "Numerical Methods — Newton-Raphson, Simpson's rule",
    ],
    youtubeId: "oSLBs_p1yic",
    channelName: "Gajendra Purohit",
    channelNote: "Best for university-level Engineering Maths in Hindi",
    playlistTitle: "Engineering Mathematics Full Course",
  },
  {
    id: "physics",
    icon: "Atom",
    accentColor: "#7c3aed",
    accentBg: "rgba(124,58,237,0.12)",
    title: "Engineering Physics",
    tagline: "The laws that govern the universe.",
    description:
      "From quantum mechanics to fiber optics — understand the physical principles that power modern technology.",
    topics: [
      "Wave Optics — interference, diffraction, polarization",
      "Quantum Mechanics — photoelectric effect, de Broglie",
      "Lasers & Fiber Optics — types, applications",
      "Electromagnetism — Maxwell's equations overview",
      "Superconductivity & Nanomaterials",
      "Ultrasonics — production, detection, applications",
    ],
    youtubeId: "N_OPRZe2BHw",
    channelName: "Alakh Pandey (Physics Wallah)",
    channelNote: "India's most loved Physics teacher — clear Hindi explanations",
    playlistTitle: "Engineering Physics Complete Series",
  },
  {
    id: "chemistry",
    icon: "FlaskConical",
    accentColor: "#f4a261",
    accentBg: "rgba(244,162,97,0.12)",
    title: "Engineering Chemistry",
    tagline: "Matter, molecules, and materials.",
    description:
      "Understand chemical bonding, thermodynamics, electrochemistry, and the materials that modern engineers work with daily.",
    topics: [
      "Chemical Bonding & Molecular Structure",
      "Thermodynamics — laws, enthalpy, entropy",
      "Electrochemistry — cells, corrosion, batteries",
      "Polymers & Plastics — types and industrial use",
      "Water Chemistry — hardness, treatment methods",
      "Spectroscopy basics — IR, NMR overview",
    ],
    youtubeId: "uVFCOfSuPTo",
    channelName: "Arvind Arora (Made Ejee)",
    channelNote: "Engaging Hindi chemistry content with real-world examples",
    playlistTitle: "Engineering Chemistry Full Course",
  },
  {
    id: "basic-electrical",
    icon: "Zap",
    accentColor: "#06d6a0",
    accentBg: "rgba(6,214,160,0.12)",
    title: "Basic Electrical Engineering",
    tagline: "Power the world with electrons.",
    description:
      "Learn circuit laws, AC/DC analysis, transformers, and electrical machines that power our modern world.",
    topics: [
      "DC Circuits — Ohm's law, KVL, KCL, mesh/node analysis",
      "AC Circuits — phasors, impedance, resonance",
      "Network Theorems — Thevenin, Norton, Superposition",
      "Transformers — working principle, efficiency",
      "Electrical Machines — DC motors, AC induction motors",
      "Measuring Instruments — multimeter, oscilloscope",
    ],
    youtubeId: "mc979OhitAg",
    channelName: "Neso Academy",
    channelNote: "Structured, crystal-clear electrical engineering series",
    playlistTitle: "Basic Electrical Engineering — Full Course",
  },
  {
    id: "electronics",
    icon: "CircuitBoard",
    accentColor: "#f72585",
    accentBg: "rgba(247,37,133,0.12)",
    title: "Electronics Engineering",
    tagline: "Diodes, transistors, and digital logic.",
    description:
      "From semiconductor physics to digital gates — build the foundation for every electronic system you'll ever design.",
    topics: [
      "Semiconductor Basics — p-n junction, depletion region",
      "Diodes — rectifiers, clippers, clampers, Zener",
      "Transistors — BJT, FET, amplifier configurations",
      "Op-Amps — inverting, non-inverting, applications",
      "Digital Logic — gates, Boolean algebra, K-maps",
      "Combinational Circuits — adders, encoders, MUX",
    ],
    youtubeId: "t3ekXB59Nkk",
    channelName: "Neso Academy",
    channelNote: "Highly rated electronics series with circuit diagrams",
    playlistTitle: "Electronics Engineering Complete Course",
  },
  {
    id: "engineering-graphics",
    icon: "PenTool",
    accentColor: "#4cc9f0",
    accentBg: "rgba(76,201,240,0.12)",
    title: "Engineering Graphics",
    tagline: "Draw it before you build it.",
    description:
      "Master orthographic projections, isometric views, and technical drawing standards — the universal language of engineers.",
    topics: [
      "Drawing Instruments & BIS Standards",
      "Lines, lettering, and geometric constructions",
      "Orthographic Projections — 1st & 3rd angle method",
      "Isometric & Perspective Views",
      "Sections of Solids — cutting planes",
      "AutoCAD Basics — 2D drawing commands",
    ],
    youtubeId: "p9pBFvaNMlQ",
    channelName: "Engineering Graphics Tutorials",
    channelNote: "Step-by-step projections explained in Hindi",
    playlistTitle: "Engineering Graphics Full Course",
  },
  {
    id: "mechanical-basics",
    icon: "Settings",
    accentColor: "#a8dadc",
    accentBg: "rgba(168,218,220,0.10)",
    title: "Mechanical Basics",
    tagline: "Forces, fluids, and machines.",
    description:
      "Understand thermodynamics, fluid mechanics, engineering materials, and the mechanical systems that move the world.",
    topics: [
      "Engineering Mechanics — statics, dynamics, friction",
      "Thermodynamics — laws, cycles, heat engines",
      "Fluid Mechanics — pressure, Bernoulli, flow types",
      "Engineering Materials — metals, alloys, composites",
      "Machine Elements — belts, gears, bearings",
      "Manufacturing Processes — casting, welding, machining",
    ],
    youtubeId: "QH2-TGUlwu4",
    channelName: "Nptelhrd (IIT Lectures)",
    channelNote: "Official IIT NPTEL lectures — gold standard content",
    playlistTitle: "Introduction to Mechanical Engineering",
  },
  {
    id: "programming-c",
    icon: "Code2",
    accentColor: "#ff9f1c",
    accentBg: "rgba(255,159,28,0.12)",
    title: "Programming in C",
    tagline: "Your first line of code starts here.",
    description:
      "Learn the foundation of all programming — variables, logic, loops, functions, pointers, and file handling in the C language.",
    topics: [
      "Introduction to C — structure, compilation, printf/scanf",
      "Data Types, Operators, and Expressions",
      "Control Flow — if/else, switch, loops",
      "Functions — declaration, recursion, scope",
      "Arrays & Strings — 1D, 2D, string functions",
      "Pointers & Dynamic Memory — malloc, free",
      "File Handling — fopen, fread, fwrite, fclose",
      "Structures & Unions",
    ],
    youtubeId: "irqbmMNs2Bo",
    channelName: "CodeWithHarry",
    channelNote: "India's favourite coding teacher — fun, fast Hindi tutorials",
    playlistTitle: "C Programming Tutorial for Beginners (Hindi)",
  },
];

export default subjects;
